name: Generate manual

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Generate manual
      run: cargo build
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "chore(docs): autogenerate manual"
        branch: ${{ github.head_ref }}

